export const ids = {
	auth: {
		roleCustomer: 'role-selection-customer-button',
		roleWalker: 'role-selection-walker-button',
		loginEmail: 'login-email-field',
		loginPassword: 'login-password-field',
		loginSubmit: 'login-submit-button',
		loginGoogle: 'login-google-button',
		registerLink: 'register-link',
		registerSubmit: 'register-submit-button',
		registerPassword: 'register-password',
		registerVerifyBanner: 'register-verify-banner',
		logoutButton: 'logout-button',
		passwordStrength: 'password-strength-indicator',
		errorBanner: 'auth-error-banner',
	},
	customer: {
		servicesTab: 'tab-services',
		bookingsTab: 'tab-bookings',
		profileTab: 'tab-profile',
		tabBarServices: 'tab-bar-services',
		tabBarBookings: 'tab-bar-bookings',
		tabBarProfile: 'tab-bar-profile',
		servicesList: 'services-list',
		serviceCard: (id: string) => `service-card-${id}`,
		serviceDetails: 'service-details',
		bookServiceButton: 'book-service-button',
		bookingLocationPicker: 'booking-location-picker',
		bookingAddLocation: 'booking-add-location',
		bookingDatePicker: 'booking-date-picker',
		bookingTimeSlot: (time: string) => `booking-time-slot-${time}`,
		bookingConfirm: 'booking-confirm-button',
		bookingNotes: 'booking-notes-field',
		bookingCancel: 'booking-cancel-button',
		bookingsList: 'bookings-list',
		bookingItem: (id: string) => `booking-item-${id}`,
		bookingReschedule: 'booking-reschedule-button',
		bookingCancelConfirm: 'booking-cancel-confirm',
		bookingFilter: 'booking-filter-button',
		profileHeader: 'profile-header',
		profileEdit: 'profile-edit-button',
		profilePets: 'profile-pets-button',
		profileSave: 'profile-save-button',
		petAdd: 'pet-add-button',
		petItem: (name: string) => `pet-item-${name}`,
		petDelete: 'pet-delete-button',
		petDeleteConfirm: 'pet-delete-confirm',
		locationsList: 'locations-list',
		locationAdd: 'location-add-button',
		locationDefault: 'location-default-button',
		paymentsTab: 'payments-tab',
		paymentMethodsList: 'payment-methods-list',
		paymentAdd: 'payment-add-button',
		paymentRemove: 'payment-remove-button',
		paymentHistory: 'payment-history-button',
		subscriptions: 'subscriptions-button',
		emptyState: 'empty-state',
		loadingIndicator: 'loading-indicator',
		errorBanner: 'error-banner',
		retryButton: 'retry-button',
	},
	walker: {
		dashboard: 'walker-dashboard',
		onDutyToggle: 'on-duty-toggle',
		todayBookingsCount: 'today-bookings-count',
		weeklyEarnings: 'weekly-earnings',
		performanceMetrics: 'performance-metrics',
		requestsTab: 'tab-requests',
		requestsList: 'pending-requests-list',
		requestItem: (id: string) => `request-item-${id}`,
		acceptBooking: 'accept-booking-button',
		declineBooking: 'decline-booking-button',
		declineReason: 'decline-reason-field',
		calendarTab: 'tab-calendar',
		calendarView: 'calendar-view',
		calendarToggleWeek: 'calendar-toggle-week',
		calendarDayItem: (date: string) => `calendar-day-${date}`,
		mapTab: 'tab-map',
		mapView: 'map-view',
		bookingMarkers: 'booking-markers',
		settingsTab: 'tab-settings',
		workingHours: 'settings-working-hours',
		serviceAreas: 'settings-service-areas',
		profileUpdate: 'settings-profile-update',
		inviteWalker: 'settings-invite-walker',
		inviteCustomer: 'settings-invite-customer',
	},
	multiTenant: {
		orgSwitcher: 'org-switcher',
		orgItem: (name: string) => `org-item-${name}`,
		brandingLogo: 'org-branding-logo',
		roleBadge: 'org-role-badge',
	},
	common: {
		backButton: 'nav-back-button',
		saveButton: 'save-button',
		confirmButton: 'confirm-button',
		toast: 'toast-message',
		permissionAllow: 'permission-allow-button',
	},
	errors: {
		offlineBanner: 'offline-banner',
		timeoutBanner: 'timeout-banner',
		unauthorizedBanner: 'unauthorized-banner',
		serverErrorBanner: 'server-error-banner',
		validationError: 'validation-error',
	},
} as const;
