# NixOS Configuration for Dog Walker Development VM
# This configuration creates a development environment with all tools pre-installed
#
# To use with UTM:
# 1. Download NixOS ISO: https://nixos.org/download (minimal ISO recommended)
# 2. Create a new VM in UTM with the ISO
# 3. Boot and run: sudo nixos-install
# 4. Copy this file to /etc/nixos/configuration.nix
# 5. Run: sudo nixos-rebuild switch

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
  ];

  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "dog-walker-dev";
  networking.networkmanager.enable = true;

  # Time zone
  time.timeZone = "America/Denver";

  # Enable flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # System packages
  environment.systemPackages = with pkgs; [
    # Development essentials
    git
    vim
    neovim
    tmux
    htop
    jq
    httpie
    curl
    wget

    # Rust toolchain
    rustup
    cargo-watch
    cargo-nextest
    sqlx-cli

    # Database
    postgresql_16

    # Container tools
    docker
    docker-compose
    kubectl
    k3d

    # Nix tools
    devenv
    direnv
    nix-direnv

    # Build tools
    gcc
    gnumake
    pkg-config
    openssl
    openssl.dev

    # GUI (optional, for desktop VM)
    # firefox
    # vscode
  ];

  # Rust environment variables
  environment.variables = {
    RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";
  };

  # PostgreSQL service
  services.postgresql = {
    enable = true;
    package = pkgs.postgresql_16;
    enableTCPIP = true;
    authentication = pkgs.lib.mkOverride 10 ''
      local all all trust
      host all all 127.0.0.1/32 trust
      host all all ::1/128 trust
    '';
    initialScript = pkgs.writeText "init.sql" ''
      CREATE USER dogwalker WITH PASSWORD 'dogwalker_dev' SUPERUSER;
      CREATE DATABASE dog_walker OWNER dogwalker;
    '';
  };

  # Docker
  virtualisation.docker.enable = true;

  # User account
  users.users.dev = {
    isNormalUser = true;
    description = "Developer";
    extraGroups = [ "wheel" "docker" "networkmanager" ];
    shell = pkgs.bash;
    initialPassword = "dev";  # Change this!
  };

  # Enable SSH
  services.openssh.enable = true;

  # Firewall
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 5432 8080 ];
  };

  # Direnv integration
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # Bash configuration
  programs.bash = {
    interactiveShellInit = ''
      eval "$(direnv hook bash)"

      # Rust
      export PATH="$HOME/.cargo/bin:$PATH"

      # Helpful aliases
      alias ll='ls -la'
      alias dc='docker compose'
      alias k='kubectl'
    '';
  };

  # System state version (don't change after install)
  system.stateVersion = "24.05";
}
